feat: fix mobile view
StyleSync/stylesync-frontend pull request #126
Opened 2024-09-04 15:06 UTC by eugenederii

2024-09-07 13:18 UTC, VadimTarasenko requested changes

2024-09-07 13:18 UTC, VadimTarasenko commented on src/modules/core/containers/burger-menu/burger-menu.tsx
> +    text: 'My bookings',
Please add translations for this buttons (reuse the same translations from header component)

2024-09-07 13:18 UTC, VadimTarasenko commented on src/modules/internationalization/dictionaries/uk.json
> +  "photo.upload.modal.caption": "Напишіть підпис...",
Replace translations with `"Описання..."`

2024-09-07 13:18 UTC, VadimTarasenko commented on src/modules/user/containers/pro-book-actions/pro-book-actions.tsx
> +        {/* <Button
you can remove this button

2024-09-07 13:18 UTC, VadimTarasenko commented on src/modules/user/containers/pro-book-actions/pro-book-actions.tsx
> +            />
display this popup on top of the button. There is `align` props in Dialog component

2024-09-19 10:13 UTC, IhorBalan commented on src/modules/internationalization/dictionaries/uk.json
> +  "photo.upload.modal.caption": "Описання...",
Maybe better to use "Опис..."?

2024-09-19 10:13 UTC, IhorBalan commented on src/modules/internationalization/dictionaries/uk.json
> +  "burger.menu.notAuthenticated": "Не автентифіковано"
Maybe better to use something like "Немає доступу", because "Не автентифіковано" sound not really correct in Ukranian

2024-10-15 11:32 UTC, IhorBalan approved these changes

2024-10-18 10:00 UTC, IhorBalan approved these changes

2024-10-18 10:00 UTC, IhorBalan commented on src/modules/user/components/professional-gallery-form/professional-gallery-form.module.scss
> +// .trigger {
Add todo or remove

2024-10-20 11:17 UTC, VadimTarasenko approved these changes

2024-10-20 11:18 UTC, merged