Add checkbox component
StyleSync/stylesync-frontend pull request #13
Opened 2023-07-18 09:58 UTC by eugenederii

2023-07-18 11:50 UTC, VadimTarasenko requested changes

2023-07-18 11:50 UTC, VadimTarasenko commented on src/modules/core/components/checkbox/checkbox.module.scss
> +  font-size: 22px;
we don't need font-size here

2023-07-18 11:50 UTC, VadimTarasenko commented on src/modules/core/components/checkbox/checkbox.module.scss
> +  padding: 9px;
use `spacing` util that based on 8px sizes.

```
@use '@/styles/utils';

padding: utils.spacing(1);
```

utils.spacing(1) is the same as 8px; utils.spacing(2) is the same as 16px and so on...

2023-07-18 11:50 UTC, VadimTarasenko commented on src/modules/core/components/checkbox/checkbox.module.scss
> +  width: fit-content;
remove width and add `display: flex;`

2023-07-18 11:50 UTC, VadimTarasenko commented on src/modules/core/components/checkbox/checkbox.module.scss
> +  border-radius: 30%;
update to `border-radius: 50%`

2023-07-18 11:50 UTC, VadimTarasenko commented on src/modules/core/components/checkbox/checkbox.module.scss
> +  background-color: #fff;
use `transparent` instead of `#fff`

2023-07-18 11:50 UTC, VadimTarasenko commented on src/modules/core/components/checkbox/checkbox.module.scss
> +    top: 11px;
change to `10px`

2023-07-18 11:50 UTC, VadimTarasenko commented on src/modules/core/components/checkbox/checkbox.module.scss
> +    left: 7px;
change to `top: 15px; left: 6px;`

2023-07-18 11:50 UTC, VadimTarasenko commented on src/modules/core/components/checkbox/checkbox.module.scss
> +label.container input:disabled + span {
you don't need `label` here. Just remove it. And replase `span` with `.checkmark`

2023-07-18 11:50 UTC, VadimTarasenko commented on src/modules/core/components/checkbox/checkbox.tsx
> +  // state
remove this comment because we don't have state anymore

2023-07-19 13:10 UTC, VadimTarasenko commented
@IhorBalan Do you have any idea why yarn.lock is changed and how we can avoid it?

2023-07-22 12:46 UTC, IhorBalan commented
> @IhorBalan Do you have any idea why yarn.lock is changed and how we can avoid it?

Well, I might have an idea about this @eugenederii did you by any chance run `npm install` and then just delete package-lock.json?
I will make updates and push into this pr to fix this issue.

2023-07-22 12:53 UTC, IhorBalan commented on src/modules/core/components/checkbox/checkbox.stories.tsx
> +    return (
let's use` render: () => {...}` and remove `return`.

2023-07-23 13:33 UTC, eugenederii commented
> > @IhorBalan Do you have any idea why yarn.lock is changed and how we can avoid it?
> 
> Well, I might have an idea about this @eugenederii did you by any chance run `npm install` and then just delete package-lock.json? I will make updates and push into this pr to fix this issue.

Hi @IhorBalan,  @VadimTarasenko yes when i started to work i made npm install and noticed that we use yarn and I delete package. json. Sorry i understand my mistake .

2023-07-25 16:00 UTC, StyleSyncAdmin commented
@IhorBalan Can you please restore `yarn.lock` one more time and then merge it. When I'm trying to run `yarn` in this branch, it doesn't change yarn.lock by some reason.

2023-07-26 07:33 UTC, VadimTarasenko approved these changes

2023-07-26 08:10 UTC, IhorBalan approved these changes

2023-07-26 08:38 UTC, merged