Map component
StyleSync/stylesync-frontend pull request #17
Opened 2023-07-27 13:19 UTC by eugenederii

2023-07-28 10:21 UTC, VadimTarasenko requested changes

2023-08-06 14:58 UTC, VadimTarasenko requested changes

2023-08-06 14:58 UTC, VadimTarasenko commented on desktop.ini
> +IconResource=C:\Windows\System32\SHELL32.dll,77
remove this file

2023-08-06 14:58 UTC, VadimTarasenko commented on src/modules/core/components/map/index.ts
add `export { Map } from './map;`

2023-08-06 14:58 UTC, VadimTarasenko commented on src/modules/core/components/map/map.module.scss
> +.custom_icon_container {
name all css classes in camelCase style - `customIconContainer`. And mayble remove `custom_` prefix in the class name. So, just `iconContainer`, `avatar` and etc...

2023-08-06 14:58 UTC, VadimTarasenko commented on src/modules/core/components/map/map.tsx
> +});
rename to `proUserMarkerIcon` and move to separate file - `~/Project/src/modules/location/constants/map.constants.ts`

2023-08-06 14:58 UTC, VadimTarasenko commented on src/modules/core/components/map/map.tsx
> +});
rename to `viewerUserMarkerIcon` and move to `~/Project/src/modules/location/constants/map.constants.ts`

2023-08-06 14:58 UTC, VadimTarasenko commented on src/modules/core/components/map/map.tsx
> +    navigator.permissions.query({ name: 'geolocation' }).then((result) => {
Probably we don't need this line. Please, check if it works without 39 line.

2023-08-06 14:58 UTC, VadimTarasenko commented on src/modules/core/components/map/map.tsx
> +    'pk.eyJ1IjoiZXVnZW5lZGVyaWkiLCJhIjoiY2xrbHMxY2t5MDZucjNlb3h0Mmc4OGVlcSJ9.stj0ywdapaAI46qlOoFV9A';
remove URL and AccessToken

2023-08-06 14:58 UTC, VadimTarasenko commented on src/modules/core/components/map/map.tsx
> +  const handleZoomOut = () => {
wrap into `useCallback`:

```ts
const handleZoomOut = useCallback(() => {
  mapRef.current?.zoomOut();
}, [])
```

And handleZoomIn too.

2023-08-06 14:58 UTC, VadimTarasenko commented on src/modules/core/components/map/map.tsx
> +          url={`https://api.mapbox.com/styles/v1/${URL}/tiles/{z}/{x}/{y}?access_token=${AccessToken}`}
do we still need mapbox here?

2023-08-06 14:58 UTC, VadimTarasenko commented on src/modules/core/components/map/map.tsx
> +              <Popup>ddd</Popup>
remove popups as we don't need them at the moment

2023-08-06 14:58 UTC, VadimTarasenko commented on src/modules/core/components/map/map.tsx
> +};
This component should be in `location` module. So, you have to create folder for location module and put this component there:

`~/Project/src/modules/location/components/map/*`

2023-08-06 14:58 UTC, VadimTarasenko commented on src/modules/core/components/zoom/index.ts
add `export { Zoom } from './zoom';`

2023-08-06 14:58 UTC, VadimTarasenko commented on src/modules/core/components/zoom/zoom.module.scss
> +  box-shadow: 0px 4px 15px 0px rgba(37, 74, 165, 0.1);
use scss variables from file 'src/styles/variables.module.scss'. In this case use `variables.$main-box-shadow` and check other places where you can use other variables.

2023-08-06 14:58 UTC, VadimTarasenko commented on src/modules/core/components/zoom/zoom.tsx
> +export const Zoom: FC<ZoomProps> = ({
Rename this component to `ZoomControl` and move to location module

2023-08-08 13:36 UTC, VadimTarasenko requested changes

2023-08-08 13:36 UTC, VadimTarasenko commented on src/modules/core/components/emoji/emoji.module.scss
remove this file

2023-08-08 13:36 UTC, VadimTarasenko commented on src/modules/core/components/zoom/zoom.module.scss
> +.zoom_control {
use camelCase for classes naming

2023-08-08 13:36 UTC, VadimTarasenko commented on src/modules/core/components/zoom/zoom.stories.tsx
> +  title: 'Core UI/Zoom',
change to `Location UI/ZoomControl` and move `zoom` folder to the `modules/location/components` and rename folder name to `zoom-control` and files like `zoom-control.tsx`...

2023-08-08 13:36 UTC, VadimTarasenko commented on src/modules/location/map/index.ts
> +export { Map } from './map';
you have to create `components` folder in the `location` and then move map to the components

2023-08-08 13:36 UTC, VadimTarasenko commented on src/modules/location/map/map.stories.tsx
> +  title: 'Core UI/Map',
rename title to `Location UI/Map`

2023-08-09 13:31 UTC, VadimTarasenko requested changes

2023-08-16 15:44 UTC, eugenederii commented on src/modules/location/constants/map.constants.ts
> +    html: `<div class=${styles.iconContainer}>
No, I havnt found another way to use this

2023-09-23 10:26 UTC, VadimTarasenko approved these changes

2023-09-23 10:28 UTC, merged