fix: make service container clickable on mobile
StyleSync/stylesync-frontend pull request #170
Opened 2024-12-16 13:55 UTC by eugenederii

2024-12-21 14:04 UTC, IhorBalan commented
The ripple animation is a bit weird on the mobile, when we click on the icon it shows for the whole service item. As for me it doesn't feel right, I suggest we remove ripple here, what do you think @VadimTarasenko, @eugenederii.
![ezgif-6-02c78de7d9](https://github.com/user-attachments/assets/a7dc2e90-cd40-488a-8c97-7af01036bcbe)

2024-12-21 14:05 UTC, IhorBalan requested changes

2024-12-21 14:05 UTC, IhorBalan commented on src/modules/service/components/service-on-professional-table-row/service-on-professional-table-row.tsx
> +          ref={rootRef}
I don't think the ripple works good here, see the comment.

2024-12-25 13:22 UTC, VadimTarasenko approved these changes

2024-12-25 15:18 UTC, merged