feat(user): add user profile crud endpoints
StyleSync/stylesync-frontend pull request #41
Opened 2023-10-11 18:42 UTC by IhorBalan

2023-10-12 07:33 UTC, VadimTarasenko requested changes
@IhorBalan Can we move `src/utils/*` to `server` folder?

2023-10-12 07:33 UTC, VadimTarasenko commented on src/app/api/auth/[...nextauth]/route.ts
> +// TODO: Fix linter when you have type and export in same line
you can write it `import NextAuth, { type NextAuthOptions } = `

2023-10-22 07:01 UTC, IhorBalan commented
> @IhorBalan Can we move `src/utils/*` to `server` folder?

`src/utils/*` belongs to the front-end part of the application, as the front-end uses it to communicate with the server. So in my opinion it's something that should be on int he `src` rather than in `server`.

2023-10-22 11:13 UTC, VadimTarasenko approved these changes

2023-10-22 11:14 UTC, merged