feat: adding logic to the contact icons
StyleSync/stylesync-frontend pull request #85
Opened 2024-04-05 18:25 UTC by eugenederii

2024-04-07 09:41 UTC, IhorBalan requested changes

2024-04-07 09:41 UTC, IhorBalan commented on src/modules/user/components/user-contact-popup/user-contact-popup.tsx
> +  const handlePhoneClick = () => {
I think in this specific case you may write this right inside onClick. I don't really like that we have to do a lot of checks before making some action. And in this particular case it won't affect performance.

2024-04-07 09:41 UTC, IhorBalan commented on src/modules/user/containers/professional-info-big-card/professional-info-big-card.tsx
> +            // @ts-ignore
Add TODO: to fix this later.

2024-04-12 09:19 UTC, IhorBalan commented on src/modules/user/components/user-contact-popup/user-contact-popup.tsx
> +              }
You don't need if here as you already made the check at the top. If it would be undefined it just won't render this button.

2024-04-12 09:19 UTC, IhorBalan commented on src/modules/user/components/user-contact-popup/user-contact-popup.tsx
> +  const handleSocialMediaClick = (url?: string | null) => {
You can also move this inside onClick and not have specific function for this.

2024-04-18 16:24 UTC, IhorBalan requested changes

2024-04-18 16:24 UTC, IhorBalan commented on src/modules/user/components/user-contact-popup/user-contact-popup.tsx
> +  const professional = props.professional;
You can use `export const UserContactPopup: FC<UserContactPopupProps> = ({ professional, ...props }) => {...}` instead of creating additional const.

2024-04-18 16:24 UTC, IhorBalan commented on src/modules/user/components/user-contact-popup/user-contact-popup.tsx
> +              }
You don't need this `if` since you have already done this check just above.

2024-04-18 16:24 UTC, IhorBalan commented on src/modules/user/components/user-contact-popup/user-contact-popup.tsx
> +              }
You don't need this `if` since you have already done this check just above.

2024-04-18 16:24 UTC, IhorBalan commented on src/modules/user/components/user-contact-popup/user-contact-popup.tsx
> +              }
You don't need this `if` since you have already done this check just above.

2024-05-12 12:43 UTC, IhorBalan approved these changes

2024-05-12 14:28 UTC, VadimTarasenko commented
@eugenederii Fix conflicts please

2024-05-14 14:06 UTC, merged