feat: added landing
StyleSync/stylesync-frontend pull request #98
Opened 2024-05-09 18:36 UTC by eugenederii

2024-05-12 15:28 UTC, IhorBalan requested changes

2024-05-12 15:28 UTC, IhorBalan commented on src/modules/landing/components/reviews-card/review-cards.tsx
> +
Remove space here

2024-05-12 15:28 UTC, IhorBalan commented on src/modules/landing/components/reviews-card/review-cards.tsx
> +    <div className=' p-4 border-2 rounded-[12px] border-[#F9F9F9] flex flex-col items-center xl:flex-row gap-6 '>
There a lot of unnecessary spaces at the start and end of the string, please remove them in whole file. And make a double check in other files.

2024-05-12 15:28 UTC, IhorBalan commented on src/modules/landing/landing-image/facebook.png
It would be nice to have svg icons.

2024-05-12 15:28 UTC, IhorBalan commented on src/modules/landing/landing-image/applePay.png
For the apple better to use icons that we have in their guideline https://developer.apple.com/app-store/marketing/guidelines/

2024-05-12 15:28 UTC, IhorBalan commented on src/modules/landing/landing-image/googlePay.png
For google better to use that they had in their guideline https://play.google.com/intl/en_us/badges/

2024-05-21 22:15 UTC, VadimTarasenko commented
<img width="1728" alt="Screenshot 2024-05-22 at 01 13 06" src="https://github.com/StyleSync/stylesync-frontend/assets/35116343/bf7bf8f4-0ac1-4cbd-af6a-99f3173af66d">

- Remove header shadow.
- Initial section should fit window height and centered (second section shouldn't be visible when scroll on top). @eugenederii

2024-05-21 22:17 UTC, VadimTarasenko commented
<img width="227" alt="Screenshot 2024-05-22 at 01 16 23" src="https://github.com/StyleSync/stylesync-frontend/assets/35116343/81c24674-71b1-459d-899d-acf935cae1f3">

Use svg for this links. On hover change color to white.

2024-05-21 22:20 UTC, VadimTarasenko commented
<img width="447" alt="Screenshot 2024-05-22 at 01 19 34" src="https://github.com/StyleSync/stylesync-frontend/assets/35116343/108ed6a8-dc23-4991-a5ce-0559f2fa6d06">

Update this buttons in according this article: https://ezedi.medium.com/how-to-get-original-googles-playstore-and-apple-s-appstore-button-for-your-app-or-website-ecbe2c66f0aa

2024-05-24 13:36 UTC, VadimTarasenko commented
<img width="1728" alt="Screenshot 2024-05-24 at 16 34 53" src="https://github.com/StyleSync/stylesync-frontend/assets/35116343/0f165d37-3f8d-4a47-893f-8ba145086555">

When we scroll to the left, slider items shouldn't be croped

2024-06-03 10:20 UTC, VadimTarasenko commented
<img width="1728" alt="Screenshot 2024-06-03 at 13 13 10" src="https://github.com/StyleSync/stylesync-frontend/assets/35116343/50a5cc9f-56f7-49b0-9153-30619fdfba9a">

Slides should have the same height

2024-06-05 10:16 UTC, VadimTarasenko commented
<img width="1728" alt="Screenshot 2024-06-05 at 13 15 34" src="https://github.com/StyleSync/stylesync-frontend/assets/35116343/4cfdf438-e56f-48c0-9066-b6e501946eab">

Improve quality of this images. Export them separately from figma.

2024-06-07 09:12 UTC, VadimTarasenko commented
<img width="1728" alt="image" src="https://github.com/StyleSync/stylesync-frontend/assets/35116343/7838417b-8771-4127-8b3c-6b415d045349">

GooglePlay and Appstore buttons overlap header @eugenederii

2024-06-19 14:09 UTC, VadimTarasenko approved these changes

2024-07-01 13:21 UTC, merged